### ISSUE TITLE
How to get the blur region mask?

### ISSUE THREAD

**Issue by guangpintao** [WillBrennan/BlurDetection2#15]
Hello, i wonder how to get the demo result as shown below using the brightness to show the blur degree:
![image](https://user-images.githubusercontent.com/32570671/110906862-8c053400-8347-11eb-91d9-f56db88a95a2.png)
It will be helpful if you can give me some instrs.

**Comment by WillBrennan** [comment]
You can see in the process code how it displays the pretty blur map; you can display it from process or save it off. 

https://github.com/WillBrennan/BlurDetection2/blob/master/process.py#L84

**Comment by guangpintao** [comment]
Thank you very much, I get it !


在 2021年3月13日 05:10，Will ***@***.***> 写道：


You can see in the process code how it displays the pretty blur map; you can display it from process or save it off.
https://github.com/WillBrennan/BlurDetection2/blob/master/process.py#L84

**Comment by kimlia545** [comment]
I saved the blur map, but it is a black image.

```
import cv2
import numpy


def fix_image_size(image: numpy.array, expected_pixels: float = 2E6):
    ratio = numpy.sqrt(expected_pixels / (image.shape[0] * image.shape[1]))
    return cv2.resize(image, (0, 0), fx=ratio, fy=ratio)


def estimate_blur(image: numpy.array, threshold: int = 100):
    if image.ndim == 3:
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    blur_map = cv2.Laplacian(image, cv2.CV_64F)
    score = numpy.var(blur_map)
    return blur_map, score, bool(score < threshold)


def pretty_blur_map(blur_map: numpy.array, sigma: int = 5, min_abs: float = 0.5):
    abs_image = numpy.abs(blur_map).astype(numpy.float32)
    abs_image[abs_image < min_abs] = min_abs

    abs_image = numpy.log(abs_image)
    cv2.blur(abs_image, (sigma, sigma))
    return cv2.medianBlur(abs_image, sigma)

image = cv2.imread('data/test.png', 0)
image = fix_image_size(image)
blur_map, score, blurry = estimate_blur(image)
cv2.imwrite('result.png', pretty_blur_map(blur_map))
```
Input 
![test](https://user-images.githubusercontent.com/72369991/214778898-a3b94fa0-8df0-4acb-a472-8082bff21b6d.png)

Output
![result](https://user-images.githubusercontent.com/72369991/214778491-02e52ef0-489d-4743-955c-43c299585332.png)
