### ISSUE TITLE
Images log twice

### ISSUE THREAD

**Issue by camjac251** [WillBrennan/BlurDetection2#7]
I'm not sure if they are scanned twice but I've noticed in the json file as well as log output in the command line that it outputs the processing and score twice for one image.

**Comment by Songloading** [comment]
Hi, are you be able to detect a directory of images? I found that the directory doesn't work for me but it works for one single image.

**Comment by camjac251** [comment]
Using directories works for me. I however only tried a directory in the same folder as the python script
`python process.py -i aligned/ -s results.json`

If you add spaces or anything non alpha numeric then it will likely break

**Comment by Songloading** [comment]
Uh... Thanks for the quick reply, But I don't think there's anything possible broke here. I just used "python process.py -i RealImage3/ -s results.json" and it cannot find the paths for images. Btw all the images are jpg format.

**Comment by Songloading** [comment]
I also comment the first line under main: "# assert sys.version_info >= (3, 7), sys.version_info" since it raises error in my system. That possibly could be the problem.

**Comment by camjac251** [comment]
I used anaconda to manage my environments and requirements for this script. Are you on Windows?

**Comment by Songloading** [comment]
I also use anaconda environments and I use Ubuntu 19. Here is the error:

AssertionError: sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)

**Comment by camjac251** [comment]
Are you using Python 3.7?

**Comment by Songloading** [comment]
I am using Python3.6

**Comment by camjac251** [comment]
Possibly try 3.7 since I used that and it worked

**Comment by Songloading** [comment]
I don't think python3.6.8 differs that much. Can you comment that line just for checking if this affects the functionality? Thanks a lot!

**Comment by WillBrennan** [comment]
This script can go down to 3.6 when f-string support was introduced.  

I can't reproduce this on my system. I've tried nested directory structures, weird characters, and symlinks. If you can provide more information then feel reopen the issue.

 When specifying paths with spaces always wrap them in quotation marks. Some characters you might need to escape as well in your path if you've got things like backslashes. 

```
python process.py -i `./my images/` 
```

. It might be that its detecting your path as a regular file
