### ISSUE TITLE
Batch process move

### ISSUE THREAD

**Issue by camjac251** [WillBrennan/BlurDetection2#9]
I was wondering if this script could have an option to move the files it detects as blurry to a separate folder, like `blurry`

I am trying to clean up a bunch of photos by deleting the blurry ones but I'm dealing with thousands so deleting them from the json would take a lot of time.

**Comment by WillBrennan** [comment]
Hey; 

It's written as a library; so it should be pretty easy to do what you're after. 

You can just do something like,

```python
import pathlib
import cv2
from blur_detection import estimate_blur

img_dir = pathlib.Path('my_directory_of_images')

for img_path in img_dir.rglob('*.png'):
    img = cv2.imread(str(img_path))
    assert image is not None

    blur_map, score, blurry = estimate_blur(image)

    if blurry:
        print(f'removing {img_path}')
        img_path.unlink()
```
